path:
  ckpt_path: "/home/mbarnig/COMPRE-TACO2/Comprehensive-Tacotron2/output/ckpt/Marylux"
  log_path: "/home/mbarnig/COMPRE-TACO2/Comprehensive-Tacotron2/output/log/Marylux"
  result_path: "/home/mbarnig/COMPRE-TACO2/Comprehensive-Tacotron2/output/result/Marylux"
optimizer:
  mask_padding: True # set model's padded outputs to padded values
  guided_attn: True # apply diagonal guided attention loss
  guided_sigma: 0.4
  guided_lambda: 1.0
  fp16_run: False
  batch_size: 64
  betas: [0.9, 0.999]
  eps: 0.00000001
  weight_decay: 0.000001
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  init_lr: 0.001
step:
  total_step: 60000
  log_step: 100
  synth_step: 5000
  val_step: 1000
  save_step: 3000
